### DISCUSSION TITLE
Setup and Autostart in a Home Assistant Operating System Installation on RP4 that works for me

### DISCUSSION THREAD

**Discussion by egamper** [adorobis/hacomfoairmqtt#40] [Show and tell]
Prepare the Virtual Environment:
------------------------------------------------------------------------------------------------------
```
sudo mkdir /config/custom_components
sudo mkdir /config/custom_components/ca350
```
	
Copy config and script from GIT https://github.com/adorobis/hacomfoairmqtt/ to /config/custom_components/ca350
/config/custom_components/ca350/ca350.py
/config/custom_components/ca350/config.ini
Edit config.ini as needed

```
python3 -m venv /config/custom_components/ca350/python3venv
source /config/custom_components/ca350/python3venv/bin/activate
pip3 install paho-mqtt
pip3 install pyserial
deactivate
```

Create /config/custom_components/ca350/ca350runner.py:
------------------------------------------------------------------------------------------------------
```
import os
pid = os.fork()

if pid > 0:
    print("parent")
else:
    print("child")
    os.system('source /config/custom_components/ca350/python3venv/bin/activate && python3 /config/custom_components/ca350/ca350.py > /config/custom_components/ca350/output.log')

```

Edit configuration.yaml:
------------------------------------------------------------------------------------------------------
```
shell_command:
  start_ca350: python3 /config/custom_components/ca350/ca350runner.py &
```

Create a HA Automation to start ca350runner.py 2 minutes after HA startup:
------------------------------------------------------------------------------------------------------
```
alias: Start Pyton3 Shell Command ca350 on HA Start
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: shell_command.start_ca350
    data: {}
mode: single
```

This configuration run stable on x86 HW with the actual ca350.py. Thanks @adorobis
