### ISSUE TITLE
The 'send_if_off' ('hold_modes') option is deprecated, please remove it from your configuration

### ISSUE THREAD

**Issue by Papi77** [adorobis/hacomfoairmqtt#37]
Hi,
Seeing this warning in HA 2022.3:

```
2022-03-04 08:19:03 WARNING (MainThread) [homeassistant.components.mqtt.climate] The 'send_if_off' option is deprecated, please remove it from your configuration
2022-03-04 08:19:03 WARNING (MainThread) [homeassistant.components.mqtt.climate] The 'hold_modes' option is deprecated, please remove it from your configuration

```
Regards,
Pawel.

**Comment by adorobis** [comment]
Are you using the latest code with HA autodiscovery? Everything works ok for me and no such warnings. Are you using some other climate devices over MQTT? Below is the full config for CA350 climate and the options that are mentioned in your warning messages are not there:
```
name: CA350 Climate
availability_topic: comfoair/status
payload_available: online
payload_not_available: offline
unique_id: ca350-ca350_climate
device:
  identifiers:
    - ca350
  name: CA350
  manufacturer: Zehnder
  model: ComfoAir 350
temperature_command_topic: comfoair/comforttemp/set
temperature_state_topic: comfoair/comforttemp
current_temperature_topic: comfoair/supplytemp
min_temp: '15'
max_temp: '27'
temp_step: '1'
modes:
  - 'off'
  - fan_only
mode_state_topic: comfoair/ha_climate_mode
mode_command_topic: comfoair/ha_climate_mode/set
fan_modes:
  - 'off'
  - low
  - medium
  - high
fan_mode_state_topic: comfoair/ha_climate_mode/fan
fan_mode_command_topic: comfoair/ha_climate_mode/fan/set
temperature_unit: C
platform: mqtt
```
